server:
    port: 8082

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  zipkin:
    url: http://localhost:9411/
    enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb://localhost:27017/catalog

exchange:
  direct: direct-exchange

queue:
   movies: movies
   series: series

routing:
  direct:
    movies: movies
    series: series
