server:
    port: 8080

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

spring:
  zipkin:
    base-url: http://zipkin-server:9411/
  rabbitmq:
    host: rabbitmq-server
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb://mongodb-server:27017/catalog

exchange:
  direct: direct-exchange

queue:
   movies: movies
   series: series

routing:
  direct:
    movies: movies
    series: series
