spring:
  zipkin:
    base-url: http://zipkin-server:9411/
  rabbitmq:
    host: rabbitmq-server
    port: 5672
    username: guest
    password: guest
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-server:3306/movies?createDatabaseIfNotExist=true
    username: root
    password: root
  
  sql:
    init:
      mode: always
      platform : mysql
      dataLocations: classPath:/movie-service.sql  
  
  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

server:
    port: 8080

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

exchange:
  direct: direct-exchange

queue:
   movies: movies

routing:
  direct:
    movies: movies
