server:
  port: 8083

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb://localhost:27017/series


exchange:
  direct: direct-exchange

queue:
   series: series

routing:
  direct:
    series: series
