server:
  port: 8080

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

spring:
  zipkin:
    base-url: http://zipkin-server:9411/
  rabbitmq:
    host: rabbitmq-server
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb://mongodb-server:27017/series


exchange:
  direct: direct-exchange

queue:
   series: series

routing:
  direct:
    series: series


management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers,circuitbreakerevents,health,info
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      getSeries:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
      postSeries:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  
  retry:
    instances: 
      getSeries:
        maxAttempts: 3
        waitDuration: 1000
      postSeries:
        maxAttempts: 3
        waitDuration: 1000